classdef Body < uint16
    enumeration
        SOLAR_SYSTEM_BARYCENTER (0)                  
        MERCURY (1)             
        VENUS (2)               
        EARTH_BARYCENTER (3)    
        MARS_BARYCENTER (4)
        JUPITER_BARYCENTER (5)
        SATURN_BARYCENTER (6)
        URANUS_BARYCENTER (7)
        NEPTUNE_BARYCENTER (8)
        PLUTO_BARYCENTER (9)
        SUN (10)
        MOON (301)
        EARTH (399)
        MARS (499)
        IO (501)
        EUROPA (502)
        GANYMEDE (503)
        CALLISTO (504)
        JUPITER (599)
        SATURN (699)
        URANUS (799)
        NEPTUNE (899)
        PLUTO (999)
        NULL(1000)
    end
end